language: python

sudo: required
services:
  - docker

branches:
  only:
    - master
    - v0.2
    - /^v\d+\.\d+\.\d+$/  # Like v0.2.0
    - /^v\d+\.\d+\.\d+\.dev\d*$/  # Like v0.2.0.dev0

python:
    - 3.3
    - 3.4
    - 3.6
env:
    matrix:
        - KAFKA_VERSION=0.9.0.1 SCALA_VERSION=2.11 PYTHONASYNCIODEBUG=1
        - KAFKA_VERSION=0.9.0.1 SCALA_VERSION=2.11 PYTHONASYNCIODEBUG=1 AIOKAFKA_NO_EXTENSIONS=1
        - KAFKA_VERSION=0.10.2.1 SCALA_VERSION=2.11 PYTHONASYNCIODEBUG=1
        - KAFKA_VERSION=0.10.2.1 SCALA_VERSION=2.11 PYTHONASYNCIODEBUG=1 AIOKAFKA_NO_EXTENSIONS=1
        - KAFKA_VERSION=0.11.0.0 SCALA_VERSION=2.12 PYTHONASYNCIODEBUG=1
        - KAFKA_VERSION=0.11.0.0 SCALA_VERSION=2.12 PYTHONASYNCIODEBUG=1 AIOKAFKA_NO_EXTENSIONS=1

before_install:
    - sudo apt-get update
    - sudo apt-get install -y libsnappy-dev

install:
    - pip install --upgrade pip setuptools wheel
    - pip install flake8
    - pip install "pytest<3.3.0" pytest-cov pytest-catchlog docker-py
    - pip install codecov
    - pip install cython
    - pip install python-snappy
    - pip install lz4 xxhash
    - pip install pathlib
    - pip install -vv -Ue .

script:
  - make cov FLAGS="-v"

after_success:
  - codecov

deploy:
  provider: pypi
  user: aio-libs-bot
  password:
    secure: "TANs/tSxdtMXjFS1Vgp1EuON2ZfvkR+26HOWDzLkITsaSQ7KxbJJ2TBr4f5OI6BTLZmGB+o3pXcphIkAWyfzEBqK8ZGoFDOOz4Lagmc/uA5Foaohw6+2uTDg6kRsCiJl0Io3zCEOwWNn+1ZfLtbkBKpkBXSR/e23YeXq6NuyEAzfEX+KnHexy4gYZv1SqQA06X8c0kJaKCH/ppwE0hW4z7+/jeHnrTxedM8kpLwaGTSsjaQs1tkqR+bJg7pi2iaL8DgB34uVT6lEWBvWd8X8HC3glZvbGYg6gZL5Hb5NdK+pMevlYX2tIA71fILL81Orx1UsbHCH6emnDtQoh8FfZ+FR8IutzaC2T5+dUdNITj9wb+1ALeN1IEAqHnGxve/V62VXsF7HHGV0s3JrdLzA9Ro3k38DKUo1ekinxqQKAULmJfY6qQHX3f61u+QGv6vAGFgrFfDo62ZfB7bixMjX72WkiK+PiDN7jioYsHyobqN8BA9UjzhcMrVk1LjzsPYg1HRRwX8dp+A605Tt3dxlb1hYfVqDoaJmkakUGb2DfSUov8LDI73ufb6/panMHm6LBVeo5MJ8MCVqvj9LZ2xQTubzXunPDY6XBvYgBKKSGkhwShzsI8nIU0oHHDuQAIMuL4v+lN9Pr9zVRx4Drxem05uTXoREFWT6usmPkimQl7I="
  distributions: "sdist"
  on:
    tags: true
    all_branches: true
    python: 3.6
