language: python

sudo: required
services:
  - docker

python:
    - 3.3
    - 3.4
    - 3.5
env:
    matrix:
        - KAFKA_VERSION=0.9.0.1 SCALA_VERSION=2.11 PYTHONASYNCIODEBUG=1

before_install:
    - sudo apt-get install -y libsnappy-dev

install:
    - pip install flake8
    - pip install pytest pytest-cov pytest-catchlog docker-py
    - pip install coveralls
    - pip install python-snappy
    - pip install wheel
    - pip install .

script:
  - make cov

after_success:
  - coveralls

deploy:
  provider: pypi
  user: andrew.svetlov
  password:
    secure: bNequAaWVcBKr296rptqi4O1ylONydRydCvUDkohQf4Oa73jx7wNXkBHPcRGlKpCMoU8zcJTh1xkEALW5eLyRgNRwvL3VJEhiy1TZCPByPKLM+uwrrwSP/G5TcSgC4nCBlUHAhun+l85CW/acOJeYFyKxiNeLHAO2thHFYdwWNI=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    all_branches: true
    python: 3.5
