language: python

sudo: required
services:
  - docker

branches:
  only:
    - master
    - v0.2
    - /^v\d+\.\d+\.\d+$/  # Like v0.2.0
    - /^v\d+\.\d+\.\d+\.dev\d*$/  # Like v0.2.0.dev0

python:
    - 3.3
    - 3.4
    - 3.6
env:
    matrix:
        - KAFKA_VERSION=0.9.0.1 SCALA_VERSION=2.11 PYTHONASYNCIODEBUG=1
        - KAFKA_VERSION=0.9.0.1 SCALA_VERSION=2.11 PYTHONASYNCIODEBUG=1 AIOKAFKA_NO_EXTENSIONS=1
        - KAFKA_VERSION=0.10.2.1 SCALA_VERSION=2.11 PYTHONASYNCIODEBUG=1
        - KAFKA_VERSION=0.10.2.1 SCALA_VERSION=2.11 PYTHONASYNCIODEBUG=1 AIOKAFKA_NO_EXTENSIONS=1
        - KAFKA_VERSION=0.11.0.0 SCALA_VERSION=2.12 PYTHONASYNCIODEBUG=1
        - KAFKA_VERSION=0.11.0.0 SCALA_VERSION=2.12 PYTHONASYNCIODEBUG=1 AIOKAFKA_NO_EXTENSIONS=1

before_install:
    - sudo apt-get update
    - sudo apt-get install -y libsnappy-dev

install:
    - pip install --upgrade pip setuptools wheel
    - pip install flake8
    - pip install "pytest<3.3.0" pytest-cov pytest-catchlog docker-py
    - pip install codecov
    - pip install cython
    - pip install python-snappy
    - pip install lz4 xxhash
    - pip install pathlib
    - pip install -vv -Ue .

script:
  - make cov FLAGS="-v"

after_success:
  - codecov

deploy:
  provider: pypi
  user: aio-libs-bot
  password:
    secure: "fh0JqGceQySbRpcmbEuajtHBa/z0hErmd777UcJlN0omHBE0kpJNoBfU8kbY3ZVI05ZRYF9xo1T2JsST6w8ZwJSEHQEG8adVc6UbLCkMiANrXwLbqpSaoScP0yD+PW7tq3tSxaQcM+ynY3w/pzu51bpky6k+bVvs5SM0WNpG1w8wecBANasybTQ99CiZCgDfwOobFUDlGpbibisp6TJT7ci9foAWu7mU9TrPlsRfwYKEAw5WRBqi8SXczV7l7BtWU9kld9zHYPexds28da0iCpBSEM1MnJh1yJ4RFQMmZxFlLLgcNYTt/SniUNEWYQTMVa6htBdiBLVtTaUYOrznAhDu01L6TsxgOKQqkxAhddtCmIxnzYDM83Fg/1n5902iwAdgZNmzVJq37EkAVwqeeFzR+phMNRod85dPwR4YDG8dkuy5W8r4H8FDe6pBXFQJf9QNKKiyKGNqBG6VMJ872T4fGFktc6C7X7++oSZ3Dv5Je6OxRVBDDg7wjxYdL3xItLCV5rvIjf3ulAUKQue6IssKJrbHG/8AFWowS8yfCpVw34ODZgGBvyifBOyPZaN8p41jElzVLHdhex6rpUbMBZYafoxDWvK7T4NOZJuYYDIjC1dQuQo/7e1kAKgN2PdS4gpVxOe7R+yiyk5IHIJBHeI/AdIkDwFbaznfVhSvyAQ="
  distributions: "sdist"
  on:
    tags: true
    all_branches: true
    python: 3.6
