# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ master ]
    tags:
      - "v0.[0-9]+.[0-9]+"
      - "v0.[0-9]+.[0-9]+.dev*"
  pull_request:
    branches: [ master ]

jobs:
  test-sanity:

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install system dependencies
      run: |
        sudo apt-get install -y libsnappy-dev libkrb5-dev

    - name: Install python dependencies
      run: |
        pip install --upgrade pip setuptools wheel
        pip install -r requirements-ci.txt
        pip install -vv -Ue .  # We set -vv to see compiler exceptions/warnings

    - name: Run Unit Tests
      run: |
        make ci-test-unit

    - name: Lint code
      run: |
        make flake

    - name: Check readme for package
      run: |
        make check-readme
