# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ master ]
    tags:
      - "v0.[0-9]+.[0-9]+"
      - "v0.[0-9]+.[0-9]+.dev*"
  pull_request:
    branches: [ master ]

jobs:
  test-sanity:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip setuptools wheel
        pip install -r requirements-ci.txt
        pip install -vv -Ue .  # We set -vv to see compiler exceptions/warnings

    - name: Run Unit Tests
      run: |
        make ci-test-unit

    - name: Lint code
      run: |
        make flake

    - name: Check readme for package
      run: |
        make check-readme
